### ISSUE TITLE
Unicode char in filename error

### ISSUE THREAD

**Issue by czebotar** [pacifica/pacifica-ingest#17]
### Pacifica Ingest version
8a7f82865ab3c51308cf3f0be1df1a930abed963

### Pacifica Core Software versions
8a7f82865ab3c51308cf3f0be1df1a930abed963

### Platform Details
EL7

### Scenario:
Unicode in filename error

### Steps to Reproduce:
UPload file with unicode character and try to download

### Expected Result:
File uploads and downlods

### Actual Result:
Internal Server Error  

```
May 15 11:30:01 ingest-1-dev systemd: Stopping user-0.slice.
May 15 11:30:15 ingest-1-dev ingestd: [2017-05-15 11:30:15,201: INFO/MainProcess] Received task: ingest.backend.tasks.ingest[939cfec2-d0ce-4620-ae1a-7b68b10c3cc6]
May 15 11:30:15 ingest-1-dev ingest: [pid: 10316|app: 0|req: 1/8] 127.0.0.1 () {50 vars in 742 bytes} [Mon May 15 11:30:14 2017] POST /upload => generated 77 bytes in 507 msecs (HTTP/1.1 200) 2 headers in 71 bytes (3134 switche
s on core 0)
May 15 11:30:16 ingest-1-dev ingestd: [2017-05-15 11:30:16,734: WARNING/PoolWorker-1] data/Proposal 45796/NMR 600 Varian (Solids) - (Nittany)/TGA RUNS/Tony_OS_09082014.ngb-ds1
May 15 11:30:17 ingest-1-dev ingestd: [2017-05-15 11:30:17,526: WARNING/PoolWorker-1] validated = True
May 15 11:30:17 ingest-1-dev ingestd: [2017-05-15 11:30:17,526: WARNING/PoolWorker-1] data/Proposal 45796/NMR 600 Varian (Solids) - (Nittany)/TGA RUNS/Tony_WS_932014.ngb-ds1
May 15 11:30:17 ingest-1-dev ingestd: [2017-05-15 11:30:17,764: WARNING/PoolWorker-1] validated = True
May 15 11:30:17 ingest-1-dev ingestd: [2017-05-15 11:30:17,782: WARNING/PoolWorker-1] /usr/lib64/python2.7/tarfile.py:2372: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting the
m as being unequal
May 15 11:30:17 ingest-1-dev ingestd: if name == member_name:
May 15 11:30:17 ingest-1-dev ingestd: [2017-05-15 11:30:17,812: ERROR/PoolWorker-1] Task ingest.backend.tasks.ingest[939cfec2-d0ce-4620-ae1a-7b68b10c3cc6] raised unexpected: KeyError("filename u'data/Proposal 45796/NMR 600 Varian (Solids) - (Nittany)/TGA RUNS/OLD_AN_102_5\\xb0C_min_08082014.ngb-ds1' not found",)
May 15 11:30:17 ingest-1-dev ingestd: Traceback (most recent call last):
May 15 11:30:17 ingest-1-dev ingestd: File "/opt/ingestd/virtualenv/lib64/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
May 15 11:30:17 ingest-1-dev ingestd: R = retval = fun(*args, **kwargs)
May 15 11:30:17 ingest-1-dev ingestd: File "/opt/ingestd/virtualenv/lib64/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
May 15 11:30:17 ingest-1-dev ingestd: return self.run(*args, **kwargs)
May 15 11:30:17 ingest-1-dev ingestd: File "/opt/ingestd/source/ingest/backend/tasks.py", line 43, in ingest
May 15 11:30:17 ingest-1-dev ingestd: success = ingest_obj.ingest()
May 15 11:30:17 ingest-1-dev ingestd: File "/opt/ingestd/source/ingest/tarutils.py", line 212, in ingest
May 15 11:30:17 ingest-1-dev ingestd: info = self.tar.getmember(path)
May 15 11:30:17 ingest-1-dev ingestd: File "/usr/lib64/python2.7/tarfile.py", line 1796, in getmember
May 15 11:30:17 ingest-1-dev ingestd: raise KeyError("filename %r not found" % name)
May 15 11:30:17 ingest-1-dev ingestd: KeyError: "filename u'data/Proposal 45796/NMR 600 Varian (Solids) - (Nittany)/TGA RUNS/OLD_AN_102_5\\xb0C_min_08082014.ngb-ds1' not found"
May 15 11:32:32 ingest-1-dev cartwsgi: [pid: 31838|app: 0|req: 4/8] 127.0.0.1 () {34 vars in 604 bytes} [Mon May 15 11:32:32 2017] POST /678e016ddf2ddfdf532091365acdcac6aafdcef822208faf8c9f37cbb369a4cb => generated 46 bytes in 24 msecs (HTTP/1.1 201) 1 headers in 56 bytes (0 switches on core 0)
May 15 11:32:32 ingest-1-dev cartd: [2017-05-15 11:32:32,640: INFO/MainProcess] Received task: cart.tasks.stage_files[7dadf4c2-4dca-4840-bd02-e07b77274e94]
May 15 11:32:33 ingest-1-dev cartd: [2017-05-15 11:32:33,310: INFO/PoolWorker-4] Task cart.tasks.stage_files[7dadf4c2-4dca-4840-bd02-e07b77274e94] succeeded in 0.0151917929761s: None
May 15 11:32:43 ingest-1-dev cartwsgi: [pid: 31838|app: 0|req: 5/9] 127.0.0.1 () {34 vars in 604 bytes} [Mon May 15 11:32:43 2017] POST /936550f6c4db570444f74338694ee1121873b258cc2ce6f2cddea9f269adb953 => generated 46 bytes in 19 msecs (HTTP/1.1 201) 1 headers in 56 bytes (0 switches on core 0)
May 15 11:32:43 ingest-1-dev cartd: [2017-05-15 11:32:43,825: INFO/MainProcess] Received task: cart.tasks.stage_files[54bf8065-2794-4052-81d5-c51036be1969]
May 15 11:32:45 ingest-1-dev cartd: [2017-05-15 11:32:45,349: INFO/PoolWorker-3] Task cart.tasks.stage_files[54bf8065-2794-4052-81d5-c51036be1969] succeeded in 0.0426718719536s: None
May 15 11:35:50 ingest-1-dev cartwsgi: [pid: 31838|app: 0|req: 6/10] 127.0.0.1 () {34 vars in 604 bytes} [Mon May 15 11:35:50 2017] POST /f9f48553e437553a2af46cc82eed17395dd3946e89f8f0b7c7017bf74b1b89e3 => generated 46 bytes in 17 msecs (HTTP/1.1 201) 1 headers in 56 bytes (0 switches on core 0)
May 15 11:35:50 ingest-1-dev cartd: [2017-05-15 11:35:50,089: INFO/MainProcess] Received task: cart.tasks.stage_files[9445e5b3-677a-40a3-be1d-67b169bb9f65]
May 15 11:35:51 ingest-1-dev cartd: [2017-05-15 11:35:51,528: INFO/PoolWorker-4] Task cart.tasks.stage_files[9445e5b3-677a-40a3-be1d-67b169bb9f65] succeeded in 0.0177621390321s: None
```

**Comment by dmlb2000** [comment]
Yup was able to reproduce the error in travis...
