### ISSUE TITLE
UnboundLocalError: local variable 'filepath' referenced before assignment

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-ingest#36]
### Pacifica Ingest version
Ref: af239a344050fe892c5f420ce19015e48d93c3d7

### Platform Details
CentOS 7.3

### Scenario:
Trying to ingest upload from uploader, can't.

### Steps to Reproduce:
Try an upload to ingest service

### Expected Result:
Upload to complete successfully and hand off to other services once ingested

### Actual Result:
Log output from uploader:
```
Jul 10 19:51:26 uprod01 myemslprod1-uploader: user_logged_in
Jul 10 19:51:26 uprod01 myemslprod1-uploader: user_from_request: user
Jul 10 19:51:26 uprod01 myemslprod1-uploader: time_out:  elapsed = 16.1389360428
Jul 10 19:51:26 uprod01 myemslprod1-uploader: timeout limit: 600
Jul 10 19:51:26 uprod01 myemslprod1-uploader: ************* good touch by user! *************
Jul 10 19:51:26 uprod01 myemslprod1-uploader: [pid: 9925|app: 0|req: 36/36] 127.0.0.1 () {52 vars in 1031 bytes} [Tue Jul 11 02:51:26 2017] POST /postData/ => generated 9 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 94 bytes (1 switches on core 0)
Jul 10 19:51:26 uprod01 myemslprod1-uploader: ************* good touch by user! *************
Jul 10 19:51:26 uprod01 myemslprod1-uploader: ************* good touch by user! *************
Jul 10 19:51:26 uprod01 myemslprod1-uploaderd: [2017-07-11 02:51:26,279: INFO/MainProcess] Received task: home.tasks.ping[cc10d604-5a73-4d04-ac2a-f24a8b83f84a]
Jul 10 19:51:26 uprod01 myemslprod1-uploader: PENDING
Jul 10 19:51:27 uprod01 myemslprod1-uploaderd: [2017-07-11 02:51:27,238: WARNING/PoolWorker-1] Pinged!
Jul 10 19:51:27 uprod01 myemslprod1-uploaderd: [2017-07-11 02:51:27,266: INFO/PoolWorker-1] Task home.tasks.ping[cc10d604-5a73-4d04-ac2a-f24a8b83f84a] succeeded in 0.0283844310325s: None
Jul 10 19:51:27 uprod01 myemslprod1-uploader: SUCCESS
Jul 10 19:51:27 uprod01 myemslprod1-uploader: Celery lives = True
Jul 10 19:51:27 uprod01 myemslprod1-uploader: [pid: 9925|app: 0|req: 37/37] 127.0.0.1 () {52 vars in 1027 bytes} [Tue Jul 11 02:51:26 2017] POST /upload/ => generated 9 bytes in 1105 msecs (HTTP/1.1 200) 3 headers in 94 bytes (1 switches on core 0)
Jul 10 19:51:27 uprod01 myemslprod1-uploaderd: [2017-07-11 02:51:27,324: INFO/MainProcess] Received task: home.tasks.upload_files[8529af4a-a537-4269-89bc-e0736bf79301]
Jul 10 19:51:27 uprod01 myemslprod1-uploader: ************* good touch by user! *************
Jul 10 19:51:27 uprod01 myemslprod1-uploader: ************* good touch by user! *************
Jul 10 19:51:27 uprod01 myemslprod1-uploader: [pid: 9925|app: 0|req: 38/38] 127.0.0.1 () {48 vars in 978 bytes} [Tue Jul 11 02:51:27 2017] GET /showStatus?_=1499741328896 => generated 1631 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
Jul 10 19:51:27 uprod01 myemslprod1-uploader: ************* good touch by user! *************
Jul 10 19:51:27 uprod01 myemslprod1-uploader: ************* good touch by user! *************
Jul 10 19:51:28 uprod01 myemslprod1-uploaderd: [2017-07-11 02:51:28,215: WARNING/PoolWorker-1] Successfully created tarfile bundle /exports/myemslprod1-uploader/07.11.2017.02.51.27.tar
Jul 10 19:51:28 uprod01 myemslprod1-uploader: *********************************************
Jul 10 19:51:28 uprod01 myemslprod1-uploader: Current state is
Jul 10 19:51:28 uprod01 myemslprod1-uploader: PROGRESS
Jul 10 19:51:28 uprod01 myemslprod1-uploader: *********************************************
Jul 10 19:51:28 uprod01 myemslprod1-uploader: The result is
Jul 10 19:51:28 uprod01 myemslprod1-uploader: {u'result': u'Bundling percent complete: 100'}
Jul 10 19:51:28 uprod01 myemslprod1-uploader: *********************************************
Jul 10 19:51:28 uprod01 myemslprod1-uploader: [pid: 9925|app: 0|req: 39/39] 127.0.0.1 () {48 vars in 976 bytes} [Tue Jul 11 02:51:27 2017] GET /incStatus?_=1499741328897 => generated 77 bytes in 681 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
Jul 10 19:51:28 uprod01 myemslprod1-uploaderd: [2017-07-11 02:51:28,463: ERROR/PoolWorker-1] Task home.tasks.upload_files[8529af4a-a537-4269-89bc-e0736bf79301] raised unexpected: ValueError('No JSON object could be decoded',)
Jul 10 19:51:28 uprod01 myemslprod1-uploaderd: Traceback (most recent call last):
Jul 10 19:51:28 uprod01 myemslprod1-uploaderd: File "/opt/myemslprod1-uploaderd/virtualenv/lib64/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
Jul 10 19:51:28 uprod01 myemslprod1-uploaderd: R = retval = fun(*args, **kwargs)
Jul 10 19:51:28 uprod01 myemslprod1-uploaderd: File "/opt/myemslprod1-uploaderd/virtualenv/lib64/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
Jul 10 19:51:28 uprod01 myemslprod1-uploaderd: return self.run(*args, **kwargs)
Jul 10 19:51:28 uprod01 myemslprod1-uploaderd: File "home/tasks.py", line 122, in upload_files
Jul 10 19:51:28 uprod01 myemslprod1-uploaderd: raise error
Jul 10 19:51:28 uprod01 myemslprod1-uploaderd: ValueError: No JSON object could be decoded
Jul 10 19:51:29 uprod01 myemslprod1-uploader: ************* good touch by user! *************
Jul 10 19:51:29 uprod01 myemslprod1-uploader: ************* good touch by user! *************
Jul 10 19:51:29 uprod01 myemslprod1-uploader: *********************************************
Jul 10 19:51:29 uprod01 myemslprod1-uploader: Current state is
Jul 10 19:51:29 uprod01 myemslprod1-uploader: DONE
Jul 10 19:51:29 uprod01 myemslprod1-uploader: *********************************************
Jul 10 19:51:29 uprod01 myemslprod1-uploader: The result is
Jul 10 19:51:29 uprod01 myemslprod1-uploader: No JSON object could be decoded
Jul 10 19:51:29 uprod01 myemslprod1-uploader: *********************************************
Jul 10 19:51:29 uprod01 myemslprod1-uploader: ------------------------------------------------------------
Jul 10 19:51:29 uprod01 myemslprod1-uploader: Exception:
Jul 10 19:51:29 uprod01 myemslprod1-uploader: Traceback (most recent call last):
Jul 10 19:51:29 uprod01 myemslprod1-uploader: File "./home/views.py", line 874, in incremental_status
Jul 10 19:51:29 uprod01 myemslprod1-uploader: ingest_result = json.loads(result)
Jul 10 19:51:29 uprod01 myemslprod1-uploader: File "/opt/rh/python27/root/usr/lib64/python2.7/json/__init__.py", line 339, in loads
Jul 10 19:51:29 uprod01 myemslprod1-uploader: return _default_decoder.decode(s)
Jul 10 19:51:29 uprod01 myemslprod1-uploader: File "/opt/rh/python27/root/usr/lib64/python2.7/json/decoder.py", line 364, in decode
Jul 10 19:51:29 uprod01 myemslprod1-uploader: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jul 10 19:51:29 uprod01 myemslprod1-uploader: File "/opt/rh/python27/root/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
Jul 10 19:51:29 uprod01 myemslprod1-uploader: raise ValueError("No JSON object could be decoded")
Jul 10 19:51:29 uprod01 myemslprod1-uploader: ValueError: No JSON object could be decoded
Jul 10 19:51:29 uprod01 myemslprod1-uploader: ------------------------------------------------------------
Jul 10 19:51:29 uprod01 myemslprod1-uploader: [pid: 9925|app: 0|req: 40/40] 127.0.0.1 () {48 vars in 976 bytes} [Tue Jul 11 02:51:29 2017] GET /incStatus?_=1499741328898 => generated 70 bytes in 32 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
```

Output from Ingest service:
```
Jul 10 20:07:28 in-0-prod ingest: Traceback (most recent call last):
Jul 10 20:07:28 in-0-prod ingest: File "/opt/ingest/source/IngestServer.py", line 64, in application
Jul 10 20:07:28 in-0-prod ingest: if filepath != '':
Jul 10 20:07:28 in-0-prod ingest: UnboundLocalError: local variable 'filepath' referenced before assignment
Jul 10 20:07:28 in-0-prod ingest: [pid: 27742|app: 0|req: 1/1] 127.0.0.1 () {50 vars in 745 bytes} [Mon Jul 10 20:07:28 2017] POST /upload => generated 0 bytes in 149 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```

@dmlb2000 Please review.

**Comment by dmlb2000** [comment]
Around the code it looks like if there is an exception at https://github.com/pacifica/pacifica-ingest/blob/502306eb6b4996e7036984731be41e0a26796f54/IngestServer.py#L58 then it would cause a reference and failure but not report it... I'll see if I can fix the logic to save the failure.
