### ISSUE TITLE
AttributeError: 'float' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-ingest#86]
### Pacifica Ingest version
v0.3.4

### Pacifica Core Software versions
v1.0alpha

### Platform Details
el7

### Scenario:
Trying an upload from MSC uploader.

### Steps to Reproduce:
Try upload from webui uploader

### Expected Result:
Success on upload 

### Actual Result:
```
May 27 16:11:38 uploader01 pacifica-ingest-backend: [2019-05-27 16:11:38,074: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'float' object has no attribute 'iteritems'",)
May 27 16:11:38 uploader01 pacifica-ingest-backend: Traceback (most recent call last):
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/celery/worker/worker.py", line 205, in start
May 27 16:11:38 uploader01 pacifica-ingest-backend: self.blueprint.start(self)
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
May 27 16:11:38 uploader01 pacifica-ingest-backend: step.start(parent)
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/celery/bootsteps.py", line 369, in start
May 27 16:11:38 uploader01 pacifica-ingest-backend: return self.obj.start()
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 317, in start
May 27 16:11:38 uploader01 pacifica-ingest-backend: blueprint.start(self)
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
May 27 16:11:38 uploader01 pacifica-ingest-backend: step.start(parent)
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 593, in start
May 27 16:11:38 uploader01 pacifica-ingest-backend: c.loop(*c.loop_args())
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/celery/worker/loops.py", line 91, in asynloop
May 27 16:11:38 uploader01 pacifica-ingest-backend: next(loop)
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
May 27 16:11:38 uploader01 pacifica-ingest-backend: cb(*cbargs)
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/kombu/transport/redis.py", line 1040, in on_readable
May 27 16:11:38 uploader01 pacifica-ingest-backend: self.cycle.on_readable(fileno)
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/kombu/transport/redis.py", line 337, in on_readable
May 27 16:11:38 uploader01 pacifica-ingest-backend: chan.handlers[type]()
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/kombu/transport/redis.py", line 724, in _brpop_read
May 27 16:11:38 uploader01 pacifica-ingest-backend: self.connection._deliver(loads(bytes_to_str(item)), dest)
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 983, in _deliver
May 27 16:11:38 uploader01 pacifica-ingest-backend: callback(message)
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 632, in _callback
May 27 16:11:38 uploader01 pacifica-ingest-backend: self.qos.append(message, message.delivery_tag)
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/kombu/transport/redis.py", line 149, in append
May 27 16:11:38 uploader01 pacifica-ingest-backend: pipe.zadd(self.unacked_index_key, time(), delivery_tag) \
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/redis/client.py", line 2320, in zadd
May 27 16:11:38 uploader01 pacifica-ingest-backend: for pair in iteritems(mapping):
May 27 16:11:38 uploader01 pacifica-ingest-backend: File "/opt/pacifica/lib/python2.7/site-packages/redis/_compat.py", line 81, in iteritems
May 27 16:11:38 uploader01 pacifica-ingest-backend: return x.iteritems()
May 27 16:11:38 uploader01 pacifica-ingest-backend: AttributeError: 'float' object has no attribute 'iteritems'
```

**Comment by dmlb2000** [comment]
So the problem I have with this stack dump is none of the Pacifica code base is referenced in it at all.

What versions of celery, redis and kombu do you have installed?

**Comment by GitBytes** [comment]
```
amqp==2.3.2
asn1crypto==0.24.0
attrs==19.1.0
backports.functools-lru-cache==1.5
billiard==3.5.0.4
celery==4.2.1
certifi==2018.10.15
cffi==1.11.5
chardet==3.0.4
cheroot==6.5.2
CherryPy==17.4.1
contextlib2==0.5.5
cryptography==2.4.2
elasticsearch==6.3.1
enum34==1.1.6
functools32==3.2.3.post2
idna==2.7
ipaddress==1.0.22
jaraco.functools==1.20
jsonschema==3.0.1
kombu==4.2.1
more-itertools==4.3.0
pacifica-cartd==0.3.11
pacifica-ingest==0.3.4
pacifica-metadata==0.10.1
pacifica-policy==0.6.5
pacifica-proxy==0.1.3
pacifica-uniqueid==0.3.4
peewee==3.9.5
portend==2.3
psutil==5.6.2
psycopg2==2.7.7
pycparser==2.19
PyMySQL==0.9.2
pyrsistent==0.15.2
python-dateutil==2.7.5
pytz==2018.7
redis==3.2.1
requests==2.20.1
six==1.12.0
tempora==1.14
urllib3==1.24.1
uWSGI==2.0.18
vine==1.1.4
zc.lockfile==1.4
```

**Comment by GitBytes** [comment]
Also, it would appear ingest celery is being restarted on each of these a bit after the fact..

**Comment by GitBytes** [comment]
Most recent out of a single upload including restart of celery:
```
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: [2019-05-28 09:02:38,166: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'float' object has no attribute 'iteritems'",)
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: Traceback (most recent call last):
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/celery/worker/worker.py", line 205, in start
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: self.blueprint.start(self)
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: step.start(parent)
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/celery/bootsteps.py", line 369, in start
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: return self.obj.start()
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 317, in start
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: blueprint.start(self)
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: step.start(parent)
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 593, in start
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: c.loop(*c.loop_args())
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/celery/worker/loops.py", line 91, in asynloop
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: next(loop)
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: cb(*cbargs)
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/kombu/transport/redis.py", line 1040, in on_readable
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: self.cycle.on_readable(fileno)
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/kombu/transport/redis.py", line 337, in on_readable
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: chan.handlers[type]()
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/kombu/transport/redis.py", line 724, in _brpop_read
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: self.connection._deliver(loads(bytes_to_str(item)), dest)
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 983, in _deliver
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: callback(message)
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 632, in _callback
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: self.qos.append(message, message.delivery_tag)
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/kombu/transport/redis.py", line 149, in append
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: pipe.zadd(self.unacked_index_key, time(), delivery_tag) \
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/redis/client.py", line 2320, in zadd
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: for pair in iteritems(mapping):
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: File "/opt/pacifia/lib/python2.7/site-packages/redis/_compat.py", line 81, in iteritems
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: return x.iteritems()
May 28 09:02:38 pacificacorehost.local pacifica-ingestd-dev[18681]: AttributeError: 'float' object has no attribute 'iteritems'
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: -------------- celery@pacificacorehost.local v4.2.1 (windowlicker)
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: ---- **** -----
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: --- * ***  * -- Linux-3.10.0-957.5.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core 2019-05-28 08:55:42
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: -- * - **** ---
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: - ** ---------- [config]
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: - ** ---------- .> app:         ingest:0x7fef99204d90
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: - ** ---------- .> transport:   redis://127.0.0.1:6379//0
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: - ** ---------- .> results:     rpc://
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: - *** --- * --- .> concurrency: 2 (prefork)
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: --- ***** -----
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: -------------- [queues]
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: .> celery           exchange=celery(direct) key=celery
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: [tasks]
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: . pacifica.ingest.tasks.ingest
May 28 09:02:39 pacificacorehost.local pacifica-ingestd-dev[18681]: . pacifica.ingest.tasks.move
May 28 09:02:39 pacificacorehost.local systemd[1]: pacifica-ingestd-dev.service: main process exited, code=exited, status=1/FAILURE
May 28 09:02:39 pacificacorehost.local systemd[1]: Unit pacifica-ingestd-dev.service entered failed state.
May 28 09:02:39 pacificacorehost.local systemd[1]: pacifica-ingestd-dev.service failed.
May 28 09:02:40 pacificacorehost.local systemd[1]: pacifica-ingestd-dev.service holdoff time over, scheduling restart.
May 28 09:02:40 pacificacorehost.local systemd[1]: Stopped Starts and manages the Pacifica based pacifica-ingestd-dev service.
May 28 09:02:40 pacificacorehost.local systemd[1]: Started Starts and manages the Pacifica based pacifica-ingestd-dev service.
May 28 09:02:40 pacificacorehost.local pacifica-ingestd-dev[19625]: /opt/pacifia/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
May 28 09:02:40 pacificacorehost.local pacifica-ingestd-dev[19625]: """)
May 28 09:02:40 pacificacorehost.local pacifica-ingestd-dev[19625]: /opt/pacifia/lib/python2.7/site-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
May 28 09:02:40 pacificacorehost.local pacifica-ingestd-dev[19625]: absolutely not recommended!
May 28 09:02:40 pacificacorehost.local pacifica-ingestd-dev[19625]: Please specify a different user using the --uid option.
May 28 09:02:40 pacificacorehost.local pacifica-ingestd-dev[19625]: User information: uid=0 euid=0 gid=0 egid=0
May 28 09:02:40 pacificacorehost.local pacifica-ingestd-dev[19625]: uid=uid, euid=euid, gid=gid, egid=egid,
May 28 09:02:40 pacificacorehost.local pacifica-ingestd-dev[19625]: [2019-05-28 09:02:40,813: INFO/MainProcess] Connected to redis://127.0.0.1:6379//0
May 28 09:02:40 pacificacorehost.local pacifica-ingestd-dev[19625]: [2019-05-28 09:02:40,820: INFO/MainProcess] mingle: searching for neighbors
May 28 09:02:41 pacificacorehost.local pacifica-ingestd-dev[19625]: [2019-05-28 09:02:41,838: INFO/MainProcess] mingle: all alone
May 28 09:02:41 pacificacorehost.local pacifica-ingestd-dev[19625]: [2019-05-28 09:02:41,853: INFO/MainProcess] celery@pacificacorehost.local ready.
```

**Comment by dmlb2000** [comment]
@GitBytes I'm wondering if your issue here is the outdated version of Kombu? The current tested version is 4.5.0.

**Comment by GitBytes** [comment]
Confirmed. Kombu >=4.5.0 is required. I was able to successfully upload a dataset with that change. Thanks!
